spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tracking_travel_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
